MCU = NRF52840

# GCC ARM Toolchain path
GNU_INSTALL_ROOT =
GNU_PREFIX = arm-none-eabi

MOUSEKEY_ENABLE = yes
BOOTMAGIC_ENABLE = full
# MIDI_ENABLE = yes
# EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = IS31FL3737
# NRF_DEBUG = yes
DEBOUNCE_TYPE = eager_pr
