MCU = NRF52840

GNU_INSTALL_ROOT =
GNU_VERSION = 8.3.0
GNU_PREFIX = arm-none-eabi

MOUSEKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
# MIDI_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = IS31FL3737
# NRF_DEBUG = yes
